### PR TITLE
Improve method for linking Julia into ESMX

### PR DESCRIPTION
**Pull request by billsacks**
Relies on fixes in https://github.com/esmf-org/esmf/pull/283

### CODE REVIEW

**Comment by billsacks** [comment]
@danrosen25 - I think this follows your suggestions... and since it follows them so closely, I made you co-author on the commit (I hope that's okay with you). I have run this nuopc Julia test using the latest changes on ESMF develop and it passes. Let me know if you notice anything that should be changed... once you approve, I'll merge this so it can get into the 8.7 release version of nuopc-app-prototypes.

**Review by danrosen25 — APPROVED** [review]
Looks good!

**Comment by danrosen25** [comment]
@billsacks I went to look at the nightly test and realized the `ESMF_TEST_NUOPC_JULIA` environment variable needs to be set to `ON` to run `ESMX_SingleModelInJuliaProto`.  The good news is that [GitHub Ubuntu Runners](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) have Julia preinstalled.  Do you want me to turn this on in the nightly test workflow?

**Comment by billsacks** [comment]
Thanks for looking into that, @danrosen25 . Yes, I'd say go ahead and try turning it on. If there are problems for any reason I'd say let's not spend time trying to figure them out (not worth spending a lot of time just to get a single test working), but if it Just Works, then great!

**Comment by danrosen25** [comment]
@billsacks I thought this would be okay so I did it anyway. I kicked the test off manually and it passed, including `PASS: ESMX_SingleModelInJuliaProto-DL`
https://github.com/esmf-org/nuopc-app-prototypes/actions/runs/10725784256/job/29744417252

**Comment by billsacks** [comment]
Awesome, thanks, let's do it then.

**Pull request merged**
